### ISSUE TITLE
Please review

### ISSUE THREAD

**Issue by kljensen** [yale-mgt-656-fall-2020/about#1]
Amy - do you mind reviewing this briefly to see what you feel like ought to be changed? I'd appreciate it!

**Comment by amy-gong** [comment]
Hi @kljensen 
Two things that I noticed from the 1st read:

1. Quizzes: 1st paragraph of quizzes mention they are 15 min long. In the 2nd half, it says students have 20 min to complete the quizzes once they start.
2. Development Environment: It may be useful to note for students if the install instructions for Mac and Windows OS are done separately from the AWS Cloud9 instructions, or if they would need to follow the instructions for AWS and Mac/Windows.

Will add more if I see / think of anything else.

**Comment by kljensen** [comment]
Thanks @amy-gong !! Closed by 3249dfd13a5a506fbcac3b7b89289fad4fffabc8 and b2a8e65232b525de5291ad9e0d4d4203f2313ac6
